services:
  viz-server:
    image: nginx:alpine
    container_name: viz-server-nginx
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro
    restart: unless-stopped
    environment:
      - NGINX_HOST=0.0.0.0
      - NGINX_PORT=80
